import { FaPlay } from "react-icons/fa";
import AnotherNavbar from "./anotherNavbar";
import Footer from "./footer";
import ModelView from "./ModelView";
import { useState } from "react";
const moviesData = [
  // Trending Movies
  {
    id: 1,
    title: "The Dark Knight",
    poster: "1.png",
    category: "Trending",
    age: "18+",
    duration: "2h 32m",
    rating: 9.0,
    type: "movie",
  },
  {
    id: 2,
    title: "Inception",
    poster: "2.png",
    category: "Trending",
    age: "16+",
    duration: "2h 28m",
    rating: 8.8,
    type: "movie",
  },
  {
    id: 3,
    title: "Interstellar",
    poster: "3.png",
    category: "Trending",
    age: "13+",
    duration: "2h 49m",
    rating: 8.6,
    type: "movie",
  },
  {
    id: 4,
    title: "Joker",
    poster: "4.png",
    category: "Trending",
    age: "18+",
    duration: "2h 2m",
    rating: 8.4,
    type: "movie",
  },
  {
    id: 5,
    title: "Avengers: Endgame",
    poster: "5.png",
    category: "Trending",
    age: "13+",
    duration: "3h 1m",
    rating: 8.4,
    type: "movie",
  },
  {
    id: 6,
    title: "Spider-Man: No Way Home",
    poster: "6.png",
    category: "Trending",
    age: "13+",
    duration: "2h 28m",
    rating: 8.3,
    type: "movie",
  },
  {
    id: 7,
    title: "The Batman",
    poster: "7.png",
    category: "Trending",
    age: "16+",
    duration: "2h 56m",
    rating: 7.9,
    type: "movie",
  },
  {
    id: 8,
    title: "Doctor Strange",
    poster: "8.png",
    category: "Trending",
    age: "13+",
    duration: "2h 6m",
    rating: 7.5,
    type: "movie",
  },
  {
    id: 9,
    title: "Black Panther",
    poster: "9.png",
    category: "Trending",
    age: "13+",
    duration: "2h 14m",
    rating: 7.3,
    type: "movie",
  },
  {
    id: 10,
    title: "Iron Man",
    poster: "10.png",
    category: "Trending",
    age: "13+",
    duration: "2h 6m",
    rating: 7.9,
    type: "movie",
  },
  {
    id: 11,
    title: "Thor: Ragnarok",
    poster: "11.png",
    category: "Trending",
    age: "13+",
    duration: "2h 10m",
    rating: 7.9,
    type: "movie",
  },
  {
    id: 12,
    title: "Captain America",
    poster: "12.png",
    category: "Trending",
    age: "13+",
    duration: "2h 4m",
    rating: 7.8,
    type: "movie",
  },
  {
    id: 19,
    title: "Venom",
    poster: "19.png",
    category: "Trending",
    age: "16+",
    duration: "1h 52m",
    rating: 6.6,
    type: "movie",
  },
  {
    id: 20,
    title: "Avatar",
    poster: "20.png",
    category: "Trending",
    age: "13+",
    duration: "2h 42m",
    rating: 7.8,
    type: "movie",
  },

  // Bollywood Movies
  {
    id: 21,
    title: "The Dark Knight",
    poster: "b1.png",
    category: "Bollywood",
    age: "18+",
    duration: "2h 32m",
    rating: 9.0,
    type: "movie",
  },
  {
    id: 22,
    title: "Inception",
    poster: "b2.png",
    category: "Bollywood",
    age: "16+",
    duration: "2h 28m",
    rating: 8.8,
    type: "movie",
  },
  {
    id: 23,
    title: "Interstellar",
    poster: "b3.png",
    category: "Bollywood",
    age: "13+",
    duration: "2h 49m",
    rating: 8.6,
    type: "movie",
  },
  {
    id: 24,
    title: "Joker",
    poster: "b4.png",
    category: "Bollywood",
    age: "18+",
    duration: "2h 2m",
    rating: 8.4,
    type: "movie",
  },
  {
    id: 25,
    title: "Avengers: Endgame",
    poster: "b5.png",
    category: "Bollywood",
    age: "13+",
    duration: "3h 1m",
    rating: 8.4,
    type: "movie",
  },
  {
    id: 26,
    title: "Spider-Man: No Way Home",
    poster: "b6.png",
    category: "Bollywood",
    age: "13+",
    duration: "2h 28m",
    rating: 8.3,
    type: "movie",
  },
  {
    id: 27,
    title: "The Batman",
    poster: "b7.png",
    category: "Bollywood",
    age: "16+",
    duration: "2h 56m",
    rating: 7.9,
    type: "movie",
  },
  {
    id: 28,
    title: "Doctor Strange",
    poster: "b8.png",
    category: "Bollywood",
    age: "13+",
    duration: "2h 6m",
    rating: 7.5,
    type: "movie",
  },
  {
    id: 29,
    title: "Black Panther",
    poster: "b9.png",
    category: "Bollywood",
    age: "13+",
    duration: "2h 14m",
    rating: 7.3,
    type: "movie",
  },
  {
    id: 30,
    title: "Iron Man",
    poster: "b10.png",
    category: "Bollywood",
    age: "13+",
    duration: "2h 6m",
    rating: 7.9,
    type: "movie",
  },
  {
    id: 31,
    title: "Thor: Ragnarok",
    poster: "b11.png",
    category: "Bollywood",
    age: "13+",
    duration: "2h 10m",
    rating: 7.9,
    type: "movie",
  },
  {
    id: 32,
    title: "Captain America",
    poster: "b12.png",
    category: "Bollywood",
    age: "13+",
    duration: "2h 4m",
    rating: 7.8,
    type: "movie",
  },
  {
    id: 33,
    title: "Justice League",
    poster: "b13.png",
    category: "Bollywood",
    age: "13+",
    duration: "2h",
    rating: 6.1,
    type: "movie",
  },
  {
    id: 34,
    title: "Aquaman",
    poster: "b14.png",
    category: "Bollywood",
    age: "13+",
    duration: "2h 23m",
    rating: 6.9,
    type: "movie",
  },
  {
    id: 35,
    title: "Wonder Woman",
    poster: "b15.png",
    category: "Bollywood",
    age: "13+",
    duration: "2h 21m",
    rating: 7.4,
    type: "movie",
  },
  {
    id: 36,
    title: "Man of Steel",
    poster: "b16.png",
    category: "Bollywood",
    age: "13+",
    duration: "2h 23m",
    rating: 7.1,
    type: "movie",
  },
  {
    id: 37,
    title: "Deadpool",
    poster: "b17.png",
    category: "Bollywood",
    age: "18+",
    duration: "1h 48m",
    rating: 8.0,
    type: "movie",
  },
  {
    id: 38,
    title: "Logan",
    poster: "b18.png",
    category: "Bollywood",
    age: "18+",
    duration: "2h 17m",
    rating: 8.1,
    type: "movie",
  },
  {
    id: 39,
    title: "Venom",
    poster: "b19.png",
    category: "Bollywood",
    age: "16+",
    duration: "1h 52m",
    rating: 6.6,
    type: "movie",
  },
  {
    id: 40,
    title: "Avatar",
    poster: "b20.png",
    category: "Bollywood",
    age: "13+",
    duration: "2h 42m",
    rating: 7.8,
    type: "movie",
  },

  // Hollywood Movies
  {
    id: 41,
    title: "The Dark Knight",
    poster: "h1.png",
    category: "Hollywood",
    age: "18+",
    duration: "2h 32m",
    rating: 9.0,
    type: "movie",
  },
  {
    id: 42,
    title: "Inception",
    poster: "h2.png",
    category: "Hollywood",
    age: "16+",
    duration: "2h 28m",
    rating: 8.8,
    type: "movie",
  },
  {
    id: 43,
    title: "Interstellar",
    poster: "h3.png",
    category: "Hollywood",
    age: "13+",
    duration: "2h 49m",
    rating: 8.6,
    type: "movie",
  },
  {
    id: 44,
    title: "Joker",
    poster: "h4.png",
    category: "Hollywood",
    age: "18+",
    duration: "2h 2m",
    rating: 8.4,
    type: "movie",
  },
  {
    id: 45,
    title: "Avengers: Endgame",
    poster: "h5.png",
    category: "Hollywood",
    age: "13+",
    duration: "3h 1m",
    rating: 8.4,
    type: "movie",
  },
  {
    id: 46,
    title: "Spider-Man: No Way Home",
    poster: "h6.png",
    category: "Hollywood",
    age: "13+",
    duration: "2h 28m",
    rating: 8.3,
    type: "movie",
  },
  {
    id: 47,
    title: "The Batman",
    poster: "h7.png",
    category: "Hollywood",
    age: "16+",
    duration: "2h 56m",
    rating: 7.9,
    type: "movie",
  },
  {
    id: 48,
    title: "Doctor Strange",
    poster: "h8.png",
    category: "Hollywood",
    age: "13+",
    duration: "2h 6m",
    rating: 7.5,
    type: "movie",
  },
  {
    id: 49,
    title: "Black Panther",
    poster: "h9.png",
    category: "Hollywood",
    age: "13+",
    duration: "2h 14m",
    rating: 7.3,
    type: "movie",
  },
  {
    id: 50,
    title: "Iron Man",
    poster: "h10.png",
    category: "Hollywood",
    age: "13+",
    duration: "2h 6m",
    rating: 7.9,
    type: "movie",
  },
  {
    id: 51,
    title: "Thor: Ragnarok",
    poster: "h11.png",
    category: "Hollywood",
    age: "13+",
    duration: "2h 10m",
    rating: 7.9,
    type: "movie",
  },
  {
    id: 52,
    title: "Captain America",
    poster: "h12.png",
    category: "Hollywood",
    age: "13+",
    duration: "2h 4m",
    rating: 7.8,
    type: "movie",
  },
  {
    id: 53,
    title: "Justice League",
    poster: "h13.png",
    category: "Hollywood",
    age: "13+",
    duration: "2h",
    rating: 6.1,
    type: "movie",
  },
  {
    id: 54,
    title: "Aquaman",
    poster: "h14.png",
    category: "Hollywood",
    age: "13+",
    duration: "2h 23m",
    rating: 6.9,
    type: "movie",
  },
  {
    id: 55,
    title: "Wonder Woman",
    poster: "h15.png",
    category: "Hollywood",
    age: "13+",
    duration: "2h 21m",
    rating: 7.4,
    type: "movie",
  },
  {
    id: 56,
    title: "Man of Steel",
    poster: "h16.png",
    category: "Hollywood",
    age: "13+",
    duration: "2h 23m",
    rating: 7.1,
    type: "movie",
  },
  {
    id: 57,
    title: "Deadpool",
    poster: "h17.png",
    category: "Hollywood",
    age: "18+",
    duration: "1h 48m",
    rating: 8.0,
    type: "movie",
  },
  {
    id: 58,
    title: "Logan",
    poster: "h18.png",
    category: "Hollywood",
    age: "18+",
    duration: "2h 17m",
    rating: 8.1,
    type: "movie",
  },
  {
    id: 59,
    title: "Venom",
    poster: "h19.png",
    category: "Hollywood",
    age: "16+",
    duration: "1h 52m",
    rating: 6.6,
    type: "movie",
  },
  {
    id: 60,
    title: "Avatar",
    poster: "h20.png",
    category: "Hollywood",
    age: "13+",
    duration: "2h 42m",
    rating: 7.8,
    type: "movie",
  },
];
const Movie = () => {
  const [selectedMovie, setSelectedMovie] = useState(null);
  const [popData, setPopupData] = useState(false);
  return (
    <>
      <AnotherNavbar />
  
      {/* Modal */}
      {popData && (
        <ModelView movie={selectedMovie} setPopData={setPopupData} />
      )}

      {/* Movie Cards */}
      <div className="movieCard">
        {moviesData.map((movie) => (
          <div
            className="movieCard-page"
            key={movie.id}
            onClick={() => {
              setSelectedMovie(movie);
              setPopupData(true); // modal open
            }}
            style={{ cursor: "pointer" }}
          >
            <img src={movie.poster} alt={movie.title} />
            {/* Hover Overlay */}
            <div className="movie-overlay">
              <button className="play-btn-card">
                <FaPlay />
              </button>

              <h6 className="movie-title">{movie.title}</h6>

              <div className="movie-meta">
                <span className="age">{movie.age}</span>
                <span>{movie.duration}</span>
                <span>⭐ {movie.rating}</span>
              </div>
            </div>
          </div>
        ))}
      </div>
      <Footer />
    </>
  );
};

export default Movie;
